
version: "2"
services:
  build-env:
    build: .
    volumes:
      - ..:/home/hostuser/Elastos.RT
    tmpfs:
      - /tmp
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
